### ISSUE TITLE
[QUESTION]: form-data vs formdata-node

### ISSUE THREAD

**Issue by xr0master** [octet-stream/form-data#1]
Hey guys. Can you explain your motivation to create this project, please?
What is different between form-data and formdata-node?

Thank you

**Comment by octet-stream** [comment]
Hello. That's a good question. In short: I decided to implement FormData other way and drop old Node.js versions.

Initially this project was just my experiment with Node.js streams and was made because of these reasons:
- form-data support old versions of Node.js, starting from [v0.12](https://github.com/form-data/form-data/blob/b16916a568a0d06f3f8a16c31f9a8b89b7844094/package.json#L37). formdata-node support [Node.js 8 and higher](https://github.com/octet-stream/form-data/blob/10bf4e653bfe990f1537d4e3bbd66d5b8bb45ea8/package.json#L16)
- form-data currently support only `.append()` method the API: https://github.com/form-data/form-data/issues/124 (I mean, look at this issue, it's unresolved for few years). formdata-node supports `.append()`, `.set()`, `.get()`, .getAll(), `.has()`, `.delete()`, `.forEach()`, `.keys()`, `.values()`, `.entries()` and `.[Symbol.iterator]` so you can use (in about) full implementation of the FormData in your Node.js projects, for tests or something else.
- formdata-node uses asynchronous iterators to read the date passed to internal storage. I'm also using different way to store everything you pass into FormData instance: all the data will be stored as-is until you start to read [FormData#stream](https://github.com/octet-stream/form-data/blob/10bf4e653bfe990f1537d4e3bbd66d5b8bb45ea8/src/lib/FormData.mjs#L290-L292) or [FormData#[Symbol.asyncIterator]](https://github.com/octet-stream/form-data/blob/10bf4e653bfe990f1537d4e3bbd66d5b8bb45ea8/src/lib/FormData.mjs#L469-L471) It allows both read and write each field in FormData.

**Comment by xr0master** [comment]
Thank you very much for such a detailed response.

I see that the packet size is pretty much the same.
What about benchmark versus competitor?
And CPU load due to while(true)?

You know, when a server has more than half a million requests, each optimization has its own price. So it is very important for me.

PS I'll be happy to have a typescript definition file as TS fanboy :)
PPS And again thank you for your amazing job!

**Comment by octet-stream** [comment]
I understand your point, but to be hones, I never thought about benchmarking in this project since this was an experiment. I'm also never wrote benchmarks, so I don't know how it works with a lots of data. Sorry about that :)
By the way, I think we might don't need while(true) in [FormData#__getField](https://github.com/octet-stream/form-data/blob/10bf4e653bfe990f1537d4e3bbd66d5b8bb45ea8/src/lib/FormData.mjs#L113) since it is the asynchronous iterator. But [StreamIterator](https://github.com/octet-stream/form-data/blob/10bf4e653bfe990f1537d4e3bbd66d5b8bb45ea8/src/lib/util/StreamIterator.mjs#L59) still needs infinite loop to read the data from Read/Readable streams. At least I don't know other way to make it works. Maybe this project needs some refactoring :)

I thought you can use standard definitions of the FormData in TS, so I didn't added them here. But if it doesn't work, I think we can fix that :)
To be honest, I barely familiar with TS, but I think we can jus get standard definitions and extend them with formdata-node specific things.

I'm also don't support any way to get size of the FormData, but I'm planning this feature for next releases.

**Comment by octet-stream** [comment]
Oh, I just realised that browser implementation uses different data types for FormData entry values, which means that you can't use it here :D
Sure I will add typings file. I guess I figured out how it could be made. Is there a way to test `.d.ts` files? Just to be sure if I'm working in the right direction since I'm barely familiar with TS.

**Comment by octet-stream** [comment]
I'm closing this thread because of inactivity.

TS typings will be added if only I'd learn TS or somebody help me with that.

**Comment by octet-stream** [comment]
@xr0master hey 👋
I've added some typings to use the library with TS. You can try it in 1.7.0 version.
