### ISSUE TITLE
Stream - files are not uploaded completely

### ISSUE THREAD

**Issue by wheelly** [octet-stream/form-data#31]
/app # node -v
v14.15.4

Files more than 1.6 Mb are not uploaded completely to the server. Happens when I use stream.

  
```
const debugStream = fs.createReadStream('/var/tmp/file_content-1617090940141');

formData.append('filedata', debugStream, filename);
const formDebug = fs.createWriteStream('form.txt');
formData.stream.pipe(formDebug);
```

So the formDebug stream has boundary section above and below the file contents

```
--NodeJSFormDataStreamBoundary6d0541f4520f3e3e3c49789061dab71d
Content-Disposition: form-data; name="filedata"; filename="file.json"
Content-Type: application/json

....<file-contents>


--NodeJSFormDataStreamBoundary6d0541f4520f3e3e3c49789061dab71d--
```

But the contents are not complete.

I checked the same code with form-data package - it's not happening there. In file-contents I get the entire file.

**Comment by octet-stream** [comment]
Hi! Thanks for your feedback. I will take a look as soon as I can.

**Comment by octet-stream** [comment]
Checked it a few times on Node v14.16.0, macOS 11.2.3 with 344mb SQL file – everything is fine. That's interesting.
But I have noticed (a while ago, actually) that sometimes the few tests are failing. So, this probably a thing. But I'm not sure what's the source of the problem.

**Comment by octet-stream** [comment]
Can you try to reproduce the problem on 3.0.0 version? I have simplified the way FormData works with streams, so it only reads the streams produced by `Blob#stream()` now (you can keep using fs.createReadStream, it will converted to File automatically).

I still have issues with tests randomly failing on my machine, but since it happens only in those where I run mocked http server, I'm starting to thing that this is not the same problem as you run into. Perhaps it appears in libraries I use for this server.

**Comment by octet-stream** [comment]
The public API has been changes, so that's how it would look like on 3.x:
```js
import fs from 'fs';
import {FormData} from 'formdata-node';

const debugStream = fs.createReadStream('/var/tmp/file_content-1617090940141');

formData.append('filedata', debugStream, filename);
const formDebug = fs.createWriteStream('form.txt');
formData.stream.pipe(formDebug);
```

**Comment by octet-stream** [comment]
I'm gonna close this because of no response. Hope v3 solves your problem.
