### ISSUE TITLE
mention some few differences 

### ISSUE THREAD

**Issue by jimmywarting** [octet-stream/form-data#43]
i where wondering if we should mention any key differences between our two packages.

your's are cjs
mine are esm

yours use older fetch-blob version still in cjs and won't update to the esm version?
yours blob/file don't use whatwg:streams for instances

is one or the other better for node-fetch?
if you use mine then you will also use the same fetch-blob version in my polyfill and node-fetch and avoid dedupl

yours are also smaller in since due to web-stream-polyfills large size

is your better for other libs like axios and superagent that are stuck with cjs?

**Comment by jimmywarting** [comment]
i don't know if you will ever update to esm and start using the latest version of fetch-blob

**Comment by octet-stream** [comment]
> i don't know if you will ever update to esm and start using the latest version of fetch-blob

I was kind of thinking to just vendor it and port for my project's purposes. Then after I switch over ESM I will just use fetch-blob, as a dependency again.

**Comment by octet-stream** [comment]
> it's also likely that nodejs will implement FormData one day also

Yeah, I heard of it. Then my package will be there as a ponyfill for older Node.js versions or other JS environments that does not have FormData.

> i where wondering if we should mention any key differences between our two packages.

Perhaps. But there's no much of a difference since you've added Node.js support. So I'm not sure what else to mention other than ESM/CJS support...

1. Both packages implement FormData per spec
2. Both has support of the files backed by FS
3. Both has TS typing, I guess. Mine has some problems with fetch because TS thinks it is URLSearchParam class for some reason. Maybe it has some incompatibilities with FormData in its type declarations. Perhaps in File or Blob. Maybe somewhere else. Couldn't find it yet.
4. Mine has both CJS and ESM support, so it can be used in both module systems.
5. Mine exposes `File`, `Blob`, and also `fileFromPath`,  `fileFromPathSync` and `isFile` as separate entry

**Comment by octet-stream** [comment]
I ended up porting `fetch-blob` into `formdata-node` to get rid of v2. When I drop CJS I will switch back to `fetch-blob` again.

**Comment by octet-stream** [comment]
I think we can add a table comparing our packages and also form-data. I think there's no much of a difference between ours (I mean, that likely only a few of them, such as having CJS support or not, others just a minor things), but it should make more sense to compare with `form-data` package, so people will be able to get this information straight from the readme rather than going to issues to find very first issue in pinned issues.

**Comment by octet-stream** [comment]
Ah! Mine targets to Node.js only, even though it has `browser` field in `package.json`, I only re-export native FormData from `globalThis` (or `window`, or `self`)

**Comment by octet-stream** [comment]
I guess the comparison table may look like this:

|                 | formdata-node | formdata-polyfill | form-data |
| --------------- | ------------- | ----------------- | --------- |
| .append()       | ✔️             | ✔️                 | ✔️*        |
| .set()          | ✔️             | ✔️                 | ❌        |
| .get()          | ✔️             | ✔️                 | ❌        |
| .getAll()       | ✔️             | ✔️                 | ❌        |
| .forEach()      | ✔️             | ✔️                 | ❌        |
| .keys()         | ✔️             | ✔️                 | ❌        |
| .values()       | ✔️             | ✔️                 | ❌        |
| .entries()      | ✔️             | ✔️                 | ❌        |
| .forEach()      | ✔️             | ✔️                 | ❌        |
| Symbol.iterator | ✔️             | ✔️                 | ❌        |
| CommonJS        | ✔️             | ❌                | ✔️         |
| ESM             | ✔️             | ✔️                 |           |
| Blob            | ✔️**           | ✔️***              | ❌        |

- \* Does not support Blob and File in entry value, but allows streams and Buffer (which is not spec-compiant, however);
- ** Have builtin implementations of Blob and File, allows native Blob and File as entry value.
- *** Support Blob and File via fetch-blob package, allows native Blob and File as entry value.

What other things we might compare in our packages and `form-data`?

**Comment by octet-stream** [comment]
Probably also worth to mention FormData `undici` and few additional features like files backed up by fs (for my package it is also builtin feature as of now)?

**Comment by jimmywarting** [comment]
fetch-blob is the only one with "files backed up by fs" support...

**Comment by octet-stream** [comment]
No. My library includes this feature too. It will be removed, however, once I mote to latest `fetch-blob` version.

**Comment by octet-stream** [comment]
For context: I made it because v2.1.2 [was broken](https://github.com/node-fetch/fetch-blob/issues/87#issuecomment-828871323) and my fix was released only in one of the v3 betas, so I had to either stick with 2.1.1 (which has its own problems, like being unable to test for [`null instanceof Blob`](https://github.com/node-fetch/fetch-blob/issues/58)) or just re-implement it myself. So, I decided to go with the second solution.

**Comment by jimmywarting** [comment]
As mention in the commit as a comment, my pkg has a built in encoder that turns formData into a blob

**Comment by octet-stream** [comment]
Sure thing 👍

**Comment by octet-stream** [comment]
Is everything correct now?

**Comment by jimmywarting** [comment]
lgtm
