### ISSUE TITLE
export built in if avalible

### ISSUE THREAD

**Issue by jimmywarting** [octet-stream/form-data#58]
Given that NodeJS v18 now have shipped FormData built in and also supporting 3th party blobs like fetch-blob, I'm going to start suggesting folks to use that instead if it's avalible

I'm also going to export the builtin if avalible in my own formdata-polyfill pkg and and do something like
`export const FormData = globalThis.FormData || Polyfill`

**Comment by octet-stream** [comment]
I don't really like the idea of exposing native FormData when it's available, because it may introduce different behaviour depending on Node.js version, just because I replaced my implementation with the Node.js'. I'd rather keep my package consistent and pure, which is why [I still can't switch to fetch-blob](https://github.com/node-fetch/fetch-blob/blob/2acec9c0dc3538c32da2825ba990dda983c09d6a/streams.cjs#L5-L50) and drop my re-implementation of Blob. I believe this is the same case scenario and those who don't need `formdata-node` anymore can make a decision to switch to Node.js' implementation themeselves, as they want to.
