### ISSUE TITLE
Allow use of require() without .default

### ISSUE THREAD

**Issue by olistic** [octet-stream/form-data#6]
Please consider adding [babel-plugin-add-module-exports](https://www.npmjs.com/package/babel-plugin-add-module-exports) so this package can be used like this:

```js
require('formdata-node')
```

Instead of:

```js
require('formdata-node').default
```

**Comment by octet-stream** [comment]
Sounds good to me. I will take a look as soon as I can. Thank you for proposing this :)

**Comment by olistic** [comment]
You know what? Let me send a PR your way!

**Comment by octet-stream** [comment]
Sure, if you want to. I guess you need to add this plugin here   https://github.com/octet-stream/form-data/blob/a663fd21f3c13a600186e6c4d742404cc5f46ccd/.babelrc.js#L14

But please don't bump Babel to latest version since it break async generators somehow (I think it happens because of Symbol.asyncIterator does not exists there anymore).
Thank you.
