### ISSUE TITLE
TypeErr source.on is not a function

### ISSUE THREAD

**Issue by iVodkabulary** [octet-stream/form-data#75]
Can you please help?

Source code is something like this:

```js
import {fileFromPath} from "formdata-node/file-from-path";
import {FormData} from "formdata-node";

const file = await fileFromPath(file_path);

let form = new FormData();
form.set('file', file);

await axios.post(requestUrl, form);
```

**Comment by octet-stream** [comment]
Hello. First of all, which version of `formdata-node` and and `axios` you use?

**Comment by iVodkabulary** [comment]
im using 
    "form-data": "^4.0.0",
    "axios": "^1.3.4",

**Comment by octet-stream** [comment]
I was asking `formdata-node` version and not `form-data` :)

**Comment by iVodkabulary** [comment]
> I was asking `formdata-node` version and not `form-data` :)

sorry i already edited above

**Comment by octet-stream** [comment]
This is because Node.js [exposed ReadableStream](https://nodejs.org/api/globals.html#class-readablestream) class staring Node.js v18. But it's available since 16.5 under [`node:stream/web` module](https://nodejs.org/api/webstreams.html#class-readablestream).

Also, `formdata-node` [requires Node.js 18](https://github.com/octet-stream/form-data/blob/7b6739b6a75c8aa51b018b04bf2003dc7969f2e3/package.json#L20), because Node.js 16 [reached EOL on 11th of Sept, 2023](https://nodejs.org/en/blog/announcements/nodejs16-eol/).

**Comment by iVodkabulary** [comment]
oh ok i understand now. I will see what can I do. Thank you for your support.

**Comment by iVodkabulary** [comment]
yes I'm planning to upgrade my server to Ubuntu 20.04 so it can support nodejs higher version then i can use the implemented formData. So i will mark this issue as resolved cause i won't try using the formdata-node anymore. Thank you very much.
