### ISSUE TITLE
[feat request]: an util extract multipart form-data from request object

### ISSUE THREAD

**Issue by JayMGurav** [octet-stream/form-data#77]
This package was really helped me generating file object from the  to push it to external service which was very particular. It would really be great if we could have a parser that could parse request object to extract multipart, form-data object

**Comment by octet-stream** [comment]
Hello! You mean `multipart/form-data` parser? There are already plenty of those, like [multer](https://npmjs.com/package/multer) and [busboy](https://www.npmjs.com/package/busboy) (or it's fork by fastify team [@fastify/busboy](https://www.npmjs.com/package/@fastify/busboy)). Also, Node.js has fetch API support since v18 or so, and you can parse form-data bodies using [BodyMixin](https://fetch.spec.whatwg.org/#body-mixin)

**Comment by JayMGurav** [comment]
Oh that's great if Node supports it natively. Thanks!
